[package]
name = "benchmark_methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { path = "../../external/risc0/risc0/build" }

[package.metadata.risc0]
methods = ["guest"]
