[package]
name = "composition-method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { path = "../../../external/risc0/risc0/zkvm", features = ["std"], default-features = false }
inner_proof-methods = { path = "../../../inner_proof/methods" }
bytemuck = "1.14"
