[workspace]
[package]
version = "0.1.0"
name = "poseidon2-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
zkhash = {git = "https://github.com/HorizenLabs/poseidon2"}
ark-serialize = "0.4"


